### ISSUE TITLE
No carriers in FO

### ISSUE THREAD

**Issue by lutek** [PrestaShop/dpdpoland#22]
After installing, the module automatically added a new carriers "DPD Krajowa (DPD Classic)" and "DPD Krajowa (DPD Classic)", but none of them appears in the front office during checkout. I tried many configuration without success.

Prestashop: 1.6.0.11

**Comment by DonatasL** [comment]
Hi,
you have to be sure that:
- Delivery countries are enabled in MODULE settings page 
- Delivery address is NOT Poland
- If carrier is set to calculate price According to total price then carrier will be disabled.

If this does not help, can you provide more information about the issue?

**Comment by lutek** [comment]
Hi,

ad1. Countries are enabled (Poland etc),
ad2. Why not Poland? "DPD Krajowa (DPD Classic)" is not Polish carrier?
ad3. Got it.
but still none appears.

I would use this module with Polish DPD, and send to EU countries including Poland.

**Comment by DonatasL** [comment]
DPD Classic is for international shipping only so if delivery country is Poland, this carrier will not be displayed (will be disabled).
Does this answer solves the issue? :)

**Comment by DonatasL** [comment]
And more thing, module settings allow to choose pricing mechanism - CSV file or carrier settings. As I understand you are using carrier settings?

**Comment by lutek** [comment]
There are three options:
DPD Krajowa (DPD Classic),
DPD Krajowa za pobraniem (COD),
DPD Międzynarodowa (DPD Classic International).

I have selected only the first two, I'm not using at the moment international shipping.

I'm confused, what should be enabled to run this module with Polish carrier.

**Comment by DonatasL** [comment]
![2015-02-25 18_45_47-modules test](https://cloud.githubusercontent.com/assets/6805817/6375275/9b55c5dc-bd1e-11e4-8fc7-41360d47ab2e.png)

The first one is called DPD standard
The second DPD standard COD
These are the settings in EN that I see. DPD Classic - the last one is for international shipping.

I think we are using different naming :)

**Comment by DonatasL** [comment]
You need to enable the first one for domestic shipment and the second one if you need COD. Does this work for you now when my info is provided?

**Comment by DonatasL** [comment]
![pricing_settings](https://cloud.githubusercontent.com/assets/6805817/6375380/56977142-bd1f-11e4-9417-8ec618b48f74.png)

One more important thing: check screenshot above and tell which setting is enabled?

**Comment by lutek** [comment]
I found the problem, empty price ;)

You mentioned that the courier appears only by the weight calculation, taking into account the possibility of setting weight limits could be good to use also an option to show by price calculation.

Thanks for help.
I have some ideas to improve I'll add them in separate threads

**Comment by DonatasL** [comment]
Glad your issue is solved.

I think this open issue should be closed?

**Comment by cubuspl42** [comment]
@DonatasL
> If carrier is set to calculate price According to total price then carrier will be disabled
Why is that? Is that a feature?
